serve:
  proxy:
    port: 4455
  api:
    port: 4456
  prometheus:
    port: 4457
    host: localhost
    metrics_path: /metrics

access_rules:
  repositories:
    - file:///rules.yml

authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: ODP_UI_DAP_URL/session/check
      preserve_path: true
      only: [ session ]

authorizers:
  allow:
    enabled: true

mutators:
  noop:
    enabled: true

errors:
  handlers:
    redirect:
      enabled: true
      config:
        to: ODP_UI_DAP_URL/
        when:
          - error: [ unauthorized ]
            request:
              header:
                accept: [ text/* ]

log:
  leak_sensitive_values: true
