- id: thredds
  upstream:
    url: http://dap.saeon.ac.za/
  match:
    url: ODP_UI_DAP_THREDDS_URL<.*>
    methods: [GET]
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: redirect
