name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync
      - name: Set up testing environment
        working-directory: ./test
        shell: bash
        run: |
          cp .env.test .env
          docker-compose up -d
          sleep 30s
      - name: Run the tests
        working-directory: ./test
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload coverage
        uses: codecov/codecov-action@v2
