name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Echo branch name
        run: |
          echo "Running on branch: ${{ steps.branch-name.outputs.current_branch }}"

      - name: Check out odp-server
        uses: actions/checkout@v4
        with:
          path: odp-server
          submodules: true

      - name: Check out odp-core
        uses: actions/checkout@v4
        with:
          repository: SAEON/odp-core
          path: odp-core
          ref: ${{ steps.branch-name.outputs.current_branch }}

      - name: Check out odp-ui
        uses: actions/checkout@v4
        with:
          repository: SAEON/odp-ui
          path: odp-ui
          ref: ${{ steps.branch-name.outputs.current_branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: odp-server
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync

      - name: Set up testing environment
        working-directory: odp-server/test
        shell: bash
        run: |
          cp .env.test .env
          docker compose up -d
          sleep 30s

      - name: Run the tests
        working-directory: odp-server/test
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          directory: odp-server/test
          token: ${{ secrets.CODECOV_TOKEN }}
